id: I3A70D20F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T09:52:33+00:00'
last_modified: '2022-06-07T22:03:39.349848+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4778
  title: ཕར་ཕྱིན་སྤྱི་དོན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F3F5:
      image_group_id: I1KG4834
      title: ''
      total_pages: 370
      order: 1
      base_file: F3F5.txt
    BE38:
      image_group_id: I1KG4835
      title: ''
      total_pages: 382
      order: 2
      base_file: BE38.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
