id: I3A70D20F
legacy_id: P004332
ocr_import_info:
  bdrc_scan_id: W1KG4778
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T09:49:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:47:52.133653+00:00'
last_modified: 2022-09-01 00:48:20.240434
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4778
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4778
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕར་ཕྱིན་སྤྱི་དོན།
  author: སེ་ར་སྨད་མཁས་གྲུབ་བསྟན་པ་དར་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.8788492937206267
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I1KG4835:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4835
      total_pages: 382
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG4835.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.8621422231576932
    legacy_id: v002
  I1KG4834:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4834
      total_pages: 370
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4834.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8995658967587595
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
