id: P004332
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4778
  title: ཕར་ཕྱིན་སྤྱི་དོན
  author: ''
  volumes:
    78e377b18ede467aaec897a8d6802aee:
      image_group_id: I1KG4834
      title: ''
      volume_number: 1
      total_pages: 370
    abb75fcdf1494992ac1ae22d2e4e6119:
      image_group_id: I1KG4835
      title: ''
      volume_number: 2
      total_pages: 382
